[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["npm ci", "npm install -g vite esbuild"]

[phases.build]
cmds = ["vite build", "esbuild server/production.ts --platform=node --packages=external --bundle --format=esm --outdir=dist"]

[phases.start]
cmd = "NODE_ENV=production node dist/production.js"

[variables]
NODE_ENV = "production"
PORT = "5000"