[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "echo 'BUILD DEBUG - Installing production dependencies only'",
  "npm ci --production",
  "echo 'BUILD DEBUG - Install completed'"
]

[phases.build]
cmds = [
  "echo 'BUILD DEBUG - Using pre-built frontend'",
  "mkdir -p dist",
  "test -f dist/index.html && echo 'Frontend already exists' || echo 'Creating frontend'",
  "ls -la dist/",
  "echo 'BUILD DEBUG - Frontend ready for deployment'"
]

[start]
cmd = "node server/production-railway.cjs"