[variables]
NODE_ENV = "production"

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx vite build --config vite.config.static.js --mode production"
]

[start]
cmd = "node static-server.js"