[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["npm ci", "npm install -g esbuild"]

[phases.build]
cmds = ["npx vite build", "npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist"]

[phases.start]
cmd = "NODE_ENV=production node dist/index.js"

[variables]
NODE_ENV = "production"
PORT = "5000"