[variables]
NODE_ENV = "production"

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx vite build --config vite.config.prod.js",
  "mkdir -p dist",
  "cp server/production.js dist/server.js"
]

[start]
cmd = "node dist/server.js"