[variables]
NODE_ENV = "production"

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx vite build --config vite.config.static.js"
]

[start]
cmd = "npx vite preview --host 0.0.0.0 --port $PORT --config vite.config.static.js"