[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "echo 'BUILD DEBUG - Using minimal dependencies'",
  "cp package.minimal.json package.json",
  "npm ci --production=false",
  "echo 'BUILD DEBUG - Install completed with minimal deps'"
]

[phases.build]
cmds = [
  "echo 'BUILD DEBUG - Starting optimized build'",
  "npx vite build --config vite.config.minimal.js",
  "echo 'BUILD DEBUG - Build completed, verifying files'",
  "ls -la dist/",
  "test -f dist/index.html && echo 'SUCCESS - Frontend built' || echo 'ERROR - Build failed'"
]

[start]
cmd = "node server/production-railway.cjs"