[variables]
NODE_ENV = "production"

[phases.install]
cmds = ["npm ci --production"]

[phases.build]
cmds = [
  "echo 'Skipping frontend build - using direct server deployment'"
]

[start]
cmd = "node server/production.js"