[variables]
NODE_ENV = "production"

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = [
  "mkdir -p dist",
  "cp -r client/index.html dist/",
  "cp -r client/public/* dist/ 2>/dev/null || true",
  "echo 'Build complete - serving React app directly'"
]

[start]
cmd = "npx serve client -s -l $PORT"