[variables]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "18"

[phases.build]
cmds = [
  "npm ci --only=production",
  "npm run build"
]

[phases.install]
cmds = ["npm ci --prefer-offline --no-audit --progress=false"]

[start]
cmd = "npm start"