[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "echo 'BUILD DEBUG - Starting npm install'",
  "npm ci --production=false",
  "echo 'BUILD DEBUG - npm install completed'"
]

[phases.build]
cmds = [
  "echo 'BUILD DEBUG - Starting build process'",
  "echo 'BUILD DEBUG - Current directory contents:'",
  "ls -la",
  "echo 'BUILD DEBUG - Creating dist directory'",
  "mkdir -p dist",
  "echo 'BUILD DEBUG - Copying static files'",
  "cp dist/index.html dist/index.html.backup || echo 'No existing index.html to backup'",
  "echo 'BUILD DEBUG - Build completed, checking dist directory'",
  "ls -la dist/",
  "echo 'BUILD DEBUG - Checking if index.html exists'",
  "test -f dist/index.html && echo 'BUILD DEBUG - index.html found' || echo 'BUILD ERROR - index.html NOT FOUND'"
]

[start]
cmd = "node server/production-railway.cjs"