[build]
builder = "nixpacks"

[deploy]
startCommand = "./railway-deploy.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"