[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "node simple-production.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"